const API_URL="https://api.homesfy.in/api/";
const GET_DATA_API="leads/projectdata/";
const STATIC_PHONE='07411782406';
const STAGING_POST_API="https://staging-api.homesfy.in/api/";
const LIVE_CREATE_LEAD="leads/create";
const FORM_ICON="http://www.w3.org/2000/svg";
const FA_ICON="uim-check-circle";
const  HOMESFY_LOGO="https://refrance.s3.ap-south-1.amazonaws.com/HomesfyLogo.png";
const HOMESFY_URL="https://www.homesfy.in/";
const HOMESFY_FACEBOOK="https://www.facebook.com/homesfy";
const HOMESFY_INSTAGRAM="https://instagram.com/homesfyindia?igshid=1hua89m9py0ue";
export {API_URL,GET_DATA_API,STATIC_PHONE,FORM_ICON,FA_ICON,HOMESFY_LOGO,HOMESFY_URL,HOMESFY_FACEBOOK,HOMESFY_INSTAGRAM,STAGING_POST_API,LIVE_CREATE_LEAD}
